apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - name: "{{ .Values.name }}"
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          {{ if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            httpGet:
              path: "{{ .Values.readinessProbe.path }}"
              port: {{ .Values.readinessProbe.port }}
          {{ end }}
          {{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: "{{ .Values.livenessProbe.path }}"
              port: {{ .Values.livenessProbe.port }}
          {{ end }}
          env:
            - name: PORT
              value: "{{ .Values.containerPort }}"
          ports:
            - containerPort: {{ .Values.containerPort }}