name: minio
description: minio kubernetes deployment
version: 0.1.0
home: https://github.com/helm/helm
sources:
  - https://github.com/helm/helm
appVersion: 3.3

dependencies:
  - name: minio
    version: "8.0.0"
    repository: "@minio"
