apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: '{{ .Values.name }}'
spec:
  version: 4.1.4
  databaseSecret:
    secretName: poll-db-auth
  storageType: Durable
  storage:
    storageClassName: {{ required "storageClassName is required" .Values.global.defaultStorageClassName }}
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  podTemplate:
    metadata:
      labels:
        app: MongoDB
  terminationPolicy: Pause
