keycloak:
  replicas: 1
  postgresql:
    # Disable PostgreSQL dependency
    enabled: false

  extraEnv: |
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"
    - name: DB_VENDOR
      value: postgres
    - name: DB_ADDR
      value: {{ .Release.Name }}-db
    - name: DB_PORT
      value: "5432"
    - name: DB_DATABASE
      value: keycloak
    - name: DB_USER_FILE
      value: /secrets/db-secret/POSTGRES_USER
    - name: DB_PASSWORD_FILE
      value: /secrets/db-secret/POSTGRES_PASSWORD
    - name: KEYCLOAK_USER_FILE
      value: /secrets/keycloak-secret/user
    - name: KEYCLOAK_PASSWORD_FILE
      value: /secrets/keycloak-secret/password
  extraEnvFrom: |
    - secretRef:
        name: 'keycloak-db-auth'
  extraVolumes: |
    - name: db-secret
      secret:
        secretName: keycloak-db-auth
    - name: keycloak-secret
      secret:
        secretName: keycloak-auth
  extraVolumeMounts: |
    - name: db-secret
      mountPath: /secrets/db-secret
      readOnly: true
    - name: keycloak-secret
      mountPath: /secrets/keycloak-secret
      readOnly: true
  service:
    httpPort: 80
