apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Values.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.name }}"
    spec:
      containers:
        - name: "{{ .Values.name }}"
          image: "{{ .Values.global.services.discord_service.name }}:{{ .Values.global.services.discord_service.tag }}"
          imagePullPolicy: "{{ .Values.global.imagePullPolicy }}"
          {{ if .Values.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            httpGet:
              path: "{{ .Values.readinessProbe.path }}"
              port: {{ .Values.readinessProbe.port }}
          {{ end }}
          {{ if .Values.livenessProbe.enabled }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            httpGet:
              path: "{{ .Values.livenessProbe.path }}"
              port: {{ .Values.livenessProbe.port }}
          {{ end }}
          env:
            - name: PORT
              value: "{{ .Values.containerPort }}"
            - name: DB_HOST
              value: "{{ .Values.database.host }}"
            - name: DB_PORT
              value: "{{ .Values.database.port }}"
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.database.username.name }}"
                  key: "{{ .Values.database.username.key }}"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.database.password.name }}"
                  key: "{{ .Values.database.password.key }}"
            - name: DISCORD_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.discord_client.id.name }}"
                  key: "{{ .Values.discord_client.id.key }}"
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: "{{ .Values.discord_client.secret.name }}"
                  key: "{{ .Values.discord_client.secret.key }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
      restartPolicy: Always
