apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.name }}'
spec:
  type: '{{ .Values.type }}'
  selector:
    app: '{{ .Values.name }}'
  ports:
    - name: grpc
      port: {{ .Values.global.grpcPort }}
      targetPort: {{ .Values.global.grpcPort }}
